package com.psk.pskindividual.mybatis.dao;

import com.psk.pskindividual.mybatis.model.University;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface UniversityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.UNIVERSITY
     *
     * @mbg.generated Sun Mar 10 15:34:33 EET 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.UNIVERSITY
     *
     * @mbg.generated Sun Mar 10 15:34:33 EET 2024
     */
    int insert(University row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.UNIVERSITY
     *
     * @mbg.generated Sun Mar 10 15:34:33 EET 2024
     */
    University selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.UNIVERSITY
     *
     * @mbg.generated Sun Mar 10 15:34:33 EET 2024
     */
    List<University> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.UNIVERSITY
     *
     * @mbg.generated Sun Mar 10 15:34:33 EET 2024
     */
    int updateByPrimaryKey(University row);
}